# display the output
print("this is the first program")
print("added via vscode")
print("new line added via vscode")
print("hi")
print("added via github")
print("added via nikki")
print("added via nikki1")
print("nikki to main")
print("new lines that are addded in the hub")
print("github to vscode")
print("moving to new branch")
print("welcome to vs code")
